sudo: false
language: node_js
node_js:
  - node
addons:
  chrome: stable
git:
  depth: 1

cache:
  directories:
    - node_modules

script: npm run travis

before_install:
  - export NODE_PATH=$(npm root -g)
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - cat ./test/unit/coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - cat ./test/unit/coverage/coverage-final.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./test/unit/coverage

  # [http://www.jackpu.com/jie-jue-travis-ci-zhong-chromezhao-bu-dao-de-ban-fa/](解决travis ci 中chrome找不到的办法)
